### ISSUE TITLE
Previous binaries are not working with flutter_rust_bridge: 1.82.0

### ISSUE THREAD

**Issue by gmpassos** [juancastillo0/wasm_run#36]
First of all, thank you for this package!

The dependency needs to be updated to the latest version, and the release binaries also need to be updated.

https://github.com/juancastillo0/wasm_run/blob/9da369cfc3c536d8a06a5718953a11a21d6645ea/packages/wasm_run/pubspec.yaml#L23

I'm using `wasm_run` to provide Wasm runtime support in my package [ApolloVM](https://github.com/ApolloVM/apollovm_dart).

Best regards.

**Comment by gmpassos** [comment]
> Hi thanks for the issue!
> 
> I am working on it. In the mena time, does pinning the version to `flutter_rust_bridge : 1.72.2` as an override work? I think the problem is a breaking change in flutter_rust_bridge

Yes, the issue is that the compiled code can't work with `flutter_rust_bridge` and `wasm_run`.

I think that it's very simple to update this. If you publish an updated version I can finalize the `wasm_run` integration and test your package.

**Comment by gmpassos** [comment]
I already have implemented the integration, but I can't test it.

https://github.com/ApolloVM/apollovm_dart/blob/wasm-runtime-io/lib/src/languages/wasm/wasm_runtime_io.dart

**Comment by gmpassos** [comment]
If you I can help to make a transparent load and resolution of the library binaries.

Take a look at:

https://github.com/gmpassos/dart_randomx/blob/master/lib/src/dart_randomx_base.dart#L71

**Comment by juancastillo0** [comment]
> If you want, I can help to make a transparent load and path resolution of the library binaries.

Thanks I will take a look!

A new version `wasm_run: ^0.0.1+2` has been release with a restriction `flutter_rust_bridge: ">=1.72.2 <1.80.0"` which does not have the breaking change. I believe this should fix it for now. 

I will be uploading `wasm_run: 0.1.0` with support for `flutter_rust_bridge: ">=1.80.0"` in the following days

**Comment by gmpassos** [comment]
Thanks for the update!

Now it's working. My tests are working now!

**Comment by gmpassos** [comment]
The only issue now is with a function that returns `void`:

```dart

void empty() {
            
}

```

Since `isVoidReturn` is not exposed, I can't check the returned `Object` by `wasm_run`. A void Function should return `null` in my framework.

**Comment by juancastillo0** [comment]
Thanks again for the issue, I will keep track of the other problems in the other issues.
