### ISSUE TITLE
Command missing: `dart run wasm_run:setup`

### ISSUE THREAD

**Issue by gmpassos** [juancastillo0/wasm_run#40]
The README mentions the command `dart run wasm_run:setup`, but it does not exist. I'm waiting for this command to enable CI execution with the correct dynamic library installation.

**Comment by juancastillo0** [comment]
Thanks for the issue!

Sorry for the delay and for the missing CLI. I just published `wasm_run 0.0.1+3` with the command. Please let me know if it works for you.

Thanks!

**Comment by gmpassos** [comment]
Thanks for the CLI.

I have integrated it with ApolloVM GitHub CI, and it's working very well:

https://github.com/ApolloVM/apollovm_dart/actions/runs/6608831508/job/17948108585

https://github.com/ApolloVM/apollovm_dart/blob/wasm-runtime-io/.github/workflows/dart.yml#L47

**Comment by gmpassos** [comment]
I have published
[apollovm: ^0.0.50](https://pub.dev/packages/apollovm)
with `wasm_run: ^0.0.1+3`
👍
