### ISSUE TITLE
Publish wasm_wit_component to pub.dev

### ISSUE THREAD

**Issue by canewsin** [juancastillo0/wasm_run#51]
can't use git dep

dart pub get --no-example
```rust
Resolving dependencies...
Because every version of wasm_wit_component from git depends on wasm_run ^0.1.0 which doesn't match any versions, wasm_wit_component from git is forbidden.
So, because wasm_test_package depends on wasm_wit_component from git, version solving failed.
```

**Comment by juancastillo0** [comment]
Hi, thanks for the issue!

You will need to override all the necessary dependencies though git in the `pubspec.yaml` 's "dependency_overrides" field

**Comment by juancastillo0** [comment]
Hi wasm_wit_component has been published, please let me know if it works for you https://pub.dev/packages/wasm_wit_component
