### ISSUE TITLE
Please publish `wasm_run 0.1.0`

### ISSUE THREAD

**Issue by gmpassos** [juancastillo0/wasm_run#53]

**Comment by gmpassos** [comment]
The current published version `wasm_run: ^0.0.1+3`, depends on `http ^0.13.5`, and this is preventing to use
it with many packages that uses `http ^1.1.0`.

**Comment by gmpassos** [comment]
FYI: @juancastillo0

**Comment by juancastillo0** [comment]
Hi, thanks for the issue! Sorry for the delay. You can find the new release at https://pub.dev/packages/wasm_run

Please let me know if it works for you

**Comment by gmpassos** [comment]
> Hi, thanks for the issue! Sorry for the delay. You can find the new release at https://pub.dev/packages/wasm_run
> 
> Please let me know if it works for you

Thanks. I will update my packages and publish them.

Best regards.

**Comment by gmpassos** [comment]
The `setup` tool is not present anymore:

https://github.com/juancastillo0/wasm_run/blob/wasm_run-v0.0.1%2B3/packages/wasm_run/bin/setup.dart

This is breaking the CI:

https://github.com/ApolloVM/apollovm_dart/actions/runs/8106450169/job/22156398339

**Comment by juancastillo0** [comment]
Thanks again. Just published wasm_run: ^0.1.0+1 with the fix

**Comment by gmpassos** [comment]
> Thanks again. Just published wasm_run: ^0.1.0+1 with the fix

Thanks,

CI is back 👍:
https://github.com/ApolloVM/apollovm_dart/actions/runs/8117866559
