### ISSUE TITLE
y_crdt - Current state?  | applyDelta?

### ISSUE THREAD

**Issue by Musta-Pollo** [juancastillo0/wasm_run#62]
Hey there,

I'm currently exploring the idea of creating a collaborative text editor using flutter_quill that utilizes the Quill Delta format for representing changes. I'm interested in achieving something similar to this: https://github.com/yjs/y-quill/tree/master.

In short, I'm considering using yjs as the underlying structure for sharing delta changes.

I came across your implementation and it got me really excited. However, I noticed that it's still a work in progress and there are some missing functions, such as `applyDelta`, that are crucial for my needs.

Could you let me know if you've used this package in your projects or if there's a way that I could contribute to help make this work?

**Comment by juancastillo0** [comment]
Hi, thanks for the issue!

I have not used `y-quill` and at the moment have not found the need for more granular text edits or advanced in this particular functionality. However, it would of course make sense to have the complete `y-rs` api in this package. I can't remember the reason I didn't add the method right away. Perhaps it required other methods or models that increased the complexity. 

However, there are multiple packages, examples and documentation that you could follow. The most important step is defining the wit interface, from that you can generate de dart and rust interface that requires to fulfill the requirement. Perhaps a suggestion is to make the api very close to that in the [`y-wasm` package](https://github.com/y-crdt/y-crdt/blob/main/ywasm/src/text.rs) and use other similar functionalities that are already implemented in the dart package as a template.

**Comment by Musta-Pollo** [comment]
Thanks for responding 👍 . I had read from that time quite a bit about this and many people tried to port it using other flutter packages but it cannot be done automatically yet and manually it seems a monumental effort.

So I will keep exploring. Another option is to use functions directly in Rust and communicate with Flutter application using the interface. I will see :)

Thank you again for letting me know.
